range: 
  low: C0
  high: B7

start:
  duration: 2
  right:
    pitch:
  left:
    pitch:
    harmonic-interval: 

right:
  melodic-interval:
    1: 1
    2: 2
    3: 3
    4: 4
    5: 5
    6: 6
    7: 7
    8: 8
    9: 9
    10: 10

  direction:
    1: down
    2: up
    3: down
    4: up
    5: down
    6: up
    7: down
    8: up
    9: down
    10: up

  duration:
    1: 1
    2: 2
    3: 3
    4: 4
    5: 5
    6: 6
    7: 7
    8: 8
    9: 9
    10: 10

left:
  harmonic-interval:
    1: 1
    2: 2
    3: 3
    4: 4
    5: 5
    6: 6
    7: 7
    8: 8
    9: 9
    10: 10

  bass-interval:
    1: 1
    2: 2
    3: 3
    4: 4
    5: 5
    6: 6
    7: 7
    8: 8
    9: 9
    10: 10

  direction:
    1: down
    2: up
    3: down
    4: up
    5: down
    6: up
    7: down
    8: up
    9: down
    10: up

  duration:
    1: 1
    2: 2
    3: 3
    4: 4
    5: 5
    6: 6
    7: 7
    8: 8
    9: 9
    10: 10
