name: Generate Score

on:  workflow_dispatch

jobs:
  build:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.6'

      - name: Go Mod Init
        run: go mod init tp
        
      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify

      - name: Go Generate
        run: go generate ./... && git diff --exit-code

      - name: Go Build
        run: go build  && ls
        
      - name: Run Command
        run: ./tp && ls
     
      - name: Download
        uses: actions/upload-artifact@v3
        with:
          name: score
          path: score.xml
